name: Build Release

on:
  push:
    tags:
      - 'release_*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [
          { name: "Linux Debug",     os: "ubuntu-22.04",     ext: "tar.gz",  config: "Debug" },
          { name: "Linux Release",   os: "ubuntu-24.04",     ext: "tar.gz",  config: "Release" },
          { name: "Windows Debug",   os: "windows-2022",     ext: "zip",     config: "Debug" },
          { name: "Windows Release", os: "windows-2022",     ext: "zip",     config: "Release" },
          { name: "macOS Debug",     os: "macos-15",         ext: "tar.gz",  config: "Debug" },
          { name: "macOS Release",   os: "macos-15",         ext: "tar.gz",  config: "Release" }
        ]
    runs-on: ${{ matrix.platform.os }}
    name: ${{ matrix.platform.name }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install llvm
        
    - name: Configure CMake
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.platform.config }} -DCLANG_TIDY_EXE=$(where clang-tidy)
        elif [ "${{ runner.os }}" = "macOS" ]; then
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.platform.config }} -DCLANG_TIDY_EXE=$(which clang-tidy) -DCMAKE_C_COMPILER=clang
        else
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.platform.config }} -DCLANG_TIDY_EXE=$(which clang-tidy)
        fi

    - name: Build
      working-directory: ./build
      run: cmake --build . --config ${{ matrix.platform.config }}

    - name: Package
      shell: bash
      run: |
        mkdir -p build/install
        cmake --install build --config ${{ matrix.platform.config }} --prefix build/install
        cd build/install
        if [ "${{ matrix.platform.ext }}" = "zip" ]; then
          7z a ../../fsminit-${{ matrix.platform.config }}-${{ matrix.platform.os }}.${{ matrix.platform.ext }} *
        else
          tar -czf ../../fsminit-${{ matrix.platform.config }}-${{ matrix.platform.os }}.${{ matrix.platform.ext }} .
        fi

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: fsminit-${{ matrix.platform.config }}-${{ matrix.platform.os }}.*
        generate_release_notes: true
