name: Build Release
on:
  push:
    tags:
      - 'release_*'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        platform: [
          {name: "Linux Debug", os: "ubuntu-22.04", ext: "tar.gz", config: "Debug"},
          {name: "Linux Release", os: "ubuntu-24.04", ext: "tar.gz", config: "Release"},
          {name: "Windows Debug", os: "windows-2022", ext: "zip", config: "Debug"},
          {name: "Windows Release", os: "windows-2022", ext: "zip", config: "Release"},
          {name: "macOS Debug", os: "macos-15", ext: "tar.gz", config: "Debug"},
          {name: "macOS Release", os: "macos-15", ext: "tar.gz", config: "Release"}
        ]
    runs-on: ${{ matrix.platform.os }}
    name: ${{ matrix.platform.name }}
    steps:
    - uses: actions/checkout@v4
    - name: Install macOS deps
      if: runner.os == 'macOS'
      run: brew install llvm
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.platform.config }}
    - name: Build
      working-directory: ./build
      run: cmake --build . --config ${{ matrix.platform.config }}
    - name: Package
      shell: bash
      run: |
        mkdir -p build/install
        cmake --install build --config ${{ matrix.platform.config }} --prefix build/install
        cd build/install
        if [ "${{ matrix.platform.ext }}" = "zip" ]; then
          7z a ../../fsminit-${{ matrix.platform.config }}-${{ matrix.platform.os }}.${{ matrix.platform.ext }} *
        else
          tar -czf ../../fsminit-${{ matrix.platform.config }}-${{ matrix.platform.os }}.${{ matrix.platform.ext }} .
        fi
    - uses: softprops/action-gh-release@v2
      with:
        files: fsminit-${{ matrix.platform.config }}-${{ matrix.platform.os }}.*
